from . import lazada_get_order
from . import lz_delete_confirmation_wizard
from . import lazada_add_product
from . import lazada_update_product
from . import lazada_get_brand
from . import lazada_get_category
from . import lazada_get_attribute
from . import lazada_get_product
from . import lazada_get_warehouse
from . import lazada_get_logistic
from . import lazada_shipping_label