# -*- coding: utf-8 -*-
{
    'name': 'JYS Lazada Integration for Odoo17',
    'version': '17.0.1.0.0',
    'category': 'Extra Tools',
    'summary': 'Lazada Integration',
    'description': 'Lazada Integration for Odoo17',
    'author': 'Jova Software',
    'maintainer': 'Jova Software',
    'company': 'Jova Software',
    'website': 'https://www.jovasoftware.com',
    'depends': ['web','base', 'contacts', 'delivery', 'sale', 'product', 'sale_management', 'stock'],
    'data': [
        'data/lazada_region_data.xml',
        'security/lazada_group.xml',
        'security/ir.model.access.csv',

        'wizard/lazada_get_order_views.xml',
        'wizard/lz_delete_confirmation_wizard_views.xml',
        'wizard/lazada_add_product_views.xml',
        'wizard/lazada_update_product_views.xml',
        'wizard/lazada_get_brand_views.xml',
        'wizard/lazada_get_category_views.xml',
        'wizard/lazada_get_attribute_views.xml',
        'wizard/lazada_get_product_views.xml',
        'wizard/lazada_get_warehouse_views.xml',
        'wizard/lazada_get_logistic_views.xml',
        'wizard/lazada_shipping_label_views.xml',
        
        'views/lazada_history_api_views.xml',
        'views/lazada_order_views.xml',
        'views/lazada_shop_views.xml',
        'views/res_company_views.xml',
        'views/lazada_region_views.xml',
        'views/delivery_carrier_views.xml',
        'views/lazada_attribute_views.xml',
        'views/lazada_brand_views.xml',
        'views/lazada_category_views.xml',
        'views/lazada_finance_views.xml',
        'views/lazada_item_views.xml',
        'views/lazada_product_image_views.xml',
        'views/lazada_warehouse_views.xml',
        'views/lazada_logistic_views.xml',
        'views/product_template_views.xml',
        'views/res_partner_views.xml',
        'views/sale_order_views.xml',
        'views/stock_picking_views.xml',
        'views/lazada_assets.xml',

        'views/jys_lazada_menu.xml'
    ],

    'license': 'Other proprietary',
    'installable': True,
}
