from . import lazada_order
from . import lazada_history_api
from . import lazada_shop
from . import res_company
from . import lazada_region
from . import account_move
from . import delivery_carrier
from . import res_partner
from . import lazada_product
from . import lazada_brand
from . import lazada_category
from . import lazada_finance
from . import lazada_attribute
from . import lazada_item
from . import lazada_warehouse
from . import lazada_logistic
from . import sale_order
from . import stock_picking
from . import product_template